# Generated by Django 5.0.6 on 2024-07-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('duration', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('experince', models.CharField(max_length=100)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('parents_phone_number', models.IntegerField(max_length=13)),
                ('telegram_link', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.courses')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.teachers')),
            ],
        ),
    ]
